name = "ABM 3"
author = "Arcane Intervention"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "882148351fb892ad09e20671ec8248af7a9da24b772f1fc4096132f84a7be200"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.109"
