#Energy Cell Array
[energy_cell_array]
	#Base energy capacity
	# Default: 1000000
	# Range: > 1
	energy_capacity = 1000000
	#Base energy transfer rate per tick
	# Default: 10000
	# Range: > 1
	energy_transfer_rate = 10000

#Portable Tank
[portable_tank]
	#Base fluid capacity of the Portable Tank in mB
	# Default: 16000
	# Range: > 1
	fluid_capacity = 16000

#Digital Furnace
[digital_furnace]
	#Base energy capacity
	# Default: 100000
	# Range: > 1
	energy_capacity = 100000
	#Base energy usage per tick
	# Default: 25
	# Range: > 1
	energy_usage = 25

#Digital Smoker
[digital_smoker]
	#Base energy capacity
	# Default: 100000
	# Range: > 1
	energy_capacity = 100000
	#Base energy usage per tick
	# Default: 10
	# Range: > 1
	energy_usage = 10

#Digital Blast Furnace
[digital_blast_furnace]
	#Base energy capacity
	# Default: 100000
	# Range: > 1
	energy_capacity = 100000
	#Base energy usage per tick
	# Default: 15
	# Range: > 1
	energy_usage = 15

#Grinder
[grinder]
	#Base energy capacity
	# Default: 100000
	# Range: > 1
	energy_capacity = 100000
	#Base energy usage per tick
	# Default: 30
	# Range: > 1
	energy_usage = 30

#Material Press
[material_press]
	#Base energy capacity
	# Default: 100000
	# Range: > 1
	energy_capacity = 100000
	#Base energy usage per tick
	# Default: 30
	# Range: > 1
	energy_usage = 30

#Arc Furnace
[arc_furnace]
	#Base energy capacity
	# Default: 100000
	# Range: > 1
	energy_capacity = 100000
	#Base energy usage per tick
	# Default: 30
	# Range: > 1
	energy_usage = 30

#HydroSieve
[hydrosieve]
	#Base energy capacity
	# Default: 100000
	# Range: > 1
	energy_capacity = 100000
	#Base energy usage per tick
	# Default: 40
	# Range: > 1
	energy_usage = 40

#ElectroCentrifuge
[electrocentrifuge]
	#Base energy capacity
	# Default: 100000
	# Range: > 1
	energy_capacity = 100000
	#Base energy usage per tick
	# Default: 40
	# Range: > 1
	energy_usage = 40

#Mixer
[mixer]
	#Base energy capacity
	# Default: 100000
	# Range: > 1
	energy_capacity = 100000
	#Base energy usage per tick
	# Default: 30
	# Range: > 1
	energy_usage = 30

#Voltaic Injector
[voltaic_injector]
	#Base energy capacity
	# Default: 100000
	# Range: > 1
	energy_capacity = 100000
	#Base energy usage per tick
	# Default: 25
	# Range: > 1
	energy_usage = 25

#Chem Lab
[chem_lab]
	#Base energy capacity
	# Default: 250000
	# Range: > 1
	energy_capacity = 250000
	#Base energy usage per tick
	# Default: 80
	# Range: > 1
	energy_usage = 80

#Assembler
[assembler]
	#Base energy capacity
	# Default: 250000
	# Range: > 1
	energy_capacity = 250000
	#Base energy usage per tick
	# Default: 80
	# Range: > 1
	energy_usage = 80

#Geo Synthesizer
[geo_synthesizer]
	#Base energy capacity
	# Default: 100000
	# Range: > 1
	energy_capacity = 100000
	#Base energy usage per tick
	# Default: 10
	# Range: > 1
	energy_usage = 10

#Atmospheric Scrubber
[atmospheric_scrubber]
	#Base energy capacity
	# Default: 250000
	# Range: > 1
	energy_capacity = 250000
	#Base energy usage per tick
	# Default: 80
	# Range: > 1
	energy_usage = 80
	#Base ticks needed for one machine operation
	# Default: 600
	# Range: > 1
	ticks_per_operation = 600

#Bio/ARU Garden
[digital_garden]
	#Base energy capacity
	# Default: 250000
	# Range: > 1
	energy_capacity = 250000
	#Base energy usage per tick
	# Default: 80
	# Range: > 1
	energy_usage = 80

#Fabricator and Auto Fabricator
[fabricators]
	#Base energy capacity
	# Default: 250000
	# Range: > 1
	energy_capacity = 250000
	#Base energy usage per tick of the Fabricator. Affects how quickly Fabrication recipes are completed.
	# Default: 2500
	# Range: > 1
	energy_usage = 2500
	#If set to true, AE2 Pattern Providers will automatically re-configure the Auto Fabricator's IO item configuration when inserting a pattern.
	ae2_pattern_auto_reconfigure = true

#Portable Generator
[portable_generator]
	#Base energy capacity
	# Default: 100000
	# Range: > 1
	energy_capacity = 100000
	#Energy generated per tick
	# Default: 80
	# Range: > 1
	energy_generation = 80
	#How much energy a fuel unit produces
	# Default: 2500
	# Range: > 1
	energy_per_fuel = 2500

#Solar Panel
[solar_panel]
	#Base energy capacity
	# Default: 100000
	# Range: > 1
	energy_capacity = 100000
	#Energy generated per tick
	# Default: 30
	# Range: > 1
	energy_generation = 30

#Repair Station
[repair_station]
	#Base energy capacity
	# Default: 250000
	# Range: > 1
	energy_capacity = 250000
	#Base energy usage per tick
	# Default: 80
	# Range: > 1
	energy_usage = 80

#Ionos Turret
[arc_turret]
	#Base energy capacity
	# Default: 200000
	# Range: > 1
	energy_capacity = 200000
	#Base energy usage per tick
	# Default: 200
	# Range: > 1
	energy_usage = 200
	#Base damage per tick
	# Default: 2.0
	# Range: 0.5 ~ 4096.0
	base_damage = 2.0

#Atmos Turret
[rocket_turret]
	#Base energy capacity
	# Default: 200000
	# Range: > 1
	energy_capacity = 200000
	#Base energy usage per rocket fired
	# Default: 10000
	# Range: > 1
	energy_usage = 10000
	#Base damage per rocket
	# Default: 40.0
	# Range: 0.5 ~ 4096.0
	base_damage = 40.0

#Noctis Turret
[railgun_turret]
	#Base energy capacity
	# Default: 2000000
	# Range: > 1
	energy_capacity = 2000000
	#Base energy usage per shot fired
	# Default: 500000
	# Range: > 1
	energy_usage = 500000
	#Base damage per shot
	# Default: 200.0
	# Range: 0.5 ~ 4096.0
	base_damage = 200.0
